#Simple Properties
simple:
  #hostname: host@mail.com
  #host_name: host@mail.com
  #host-name: host@mail.com
  #HOST_NAME: host@mail.com
  hostName: host@mail:com
  port: 9000
  from: mailer@mail.com

#Nested Properties
nested:
  host: mailer@mail.com
  port: 9000
  from: mailer@mail.com
  allowed-methods: GET, POST
  ##List properties
  defaultRecipients:
    - admin@mail.com
    - wner@mail.com
  ##Map Properties
  additionalHeaders.redelivery: true
  additionalHeaders.secure: true
  additionalHeaders.X-ABC: 123456
  ##Object properties
  credentials.username: john2
  credentials.password: password2
  credentials.authMethod: SHA2
  ##Properties properties
  properties:
    oracle.net.keepAlive: true
    oracle.net.TCP_KEEPIDLE: 60

#Bean Properties
bean:
  a:
    name: a
    size: 10
    password: ENC(+wfrQ3bUXp4UuP9JKa0jCPTRqZknDuzoQwFLZ+oXoJY=)
  b:
    name: b
    size: 100
    password: ENC(UVPMnkO2KiDdsRq/14QN7/EVIENydJJzPVNDD84C0DE=)

#Validation Properties
validation:
  hostName: host@mail.com
  port: 9000
  from: mailer@mail.com
  authMethod: SHA1

#Conversion Properties
##Duration
duration:
  timeInDefaultUnit: 10
  timeBySpec: 9ns
  timeInDays: 2
##DataSize
dataSize:
  sizeInDefaultUnit: 300
  sizeBySpec: 2GB
  sizeInTB: 4
##Custom
custom:
  employee: john,2000

#Immutable Properties
immutable:
  authMethod: basic
  username: john
  password: password

#Value
value:
  host: example.zxf.com
  port: 8080

feature:
  toggles:
    - feature: FeatureA
      type: None
      target:
      toggle: Y
    - feature: FeatureA
      type: User
      target: UserA
      toggle: N
    - feature: FeatureB
      type: None
      target:
      toggle: N
    - feature: FeatureB
      type: Case
      target: CaseA
      toggle: Y
yaml:
  a:
    b:
      c: 123
  a.d.d: 234
yaml.a.d.e: 345